name: Output between jobs

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.var3 }}

    steps:
      - id: step1
        run: echo "::set-output name=var3::${{github.ref}}"

  job2:
    runs-on: ubuntu-latest

    needs: job1

    steps:
      - run: echo ${{ needs.job1.outputs.output1 }}
